create table user
(
USER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
EMAIL VARCHAR(30) UNIQUE,
PASSWORD VARCHAR(30),
CREATED_BY VARCHAR(30),
CREATED_ON DATE
CART_ID INT UNIQUE,
ROLE_ID INT,
UPDATED_ON DATE,
UPDATED_BY VARCHAR(30),
FOREIGN KEY (CART_ID) REFERENCES SHOP_CART(CART_ID),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) /* (many to one relation with role table) */
); /* (one to one relation with shop_cart table) */


create table role
(
ROLE_ID INT PRIMARY KEY,
ROLE_NAME VARCHAR(30)
);

create table user_history
(
ID INT PRIMARY KEY,
DESCRIPTION VARCHAR(30),
USER_ID INT,
CREATED_BY VARCHAR(30),
CREATED_ON DATE,
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
); /* (many to one relation with user table) */

CREATE TABLE SHOP_CART(
CART_ID INT PRIMARY KEY,
CREATED_BY VARCHAR(30),
CREATED_ON DATE,
UPDATED_BY VARCHAR(30),
UPDATED_ON DATE
);

CREATE TABLE PRODUCT
(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(30),
DESCRIPTION VARCHAR(30),
CREATED_BY VARCHAR(30),
CREATED_ON DATE,
UPDATED_BY VARCHAR(30),
UPDATED_ON DATE,
PRICE INT,
QUANTITY INT,
CART_ID INT,
FOREIGN KEY (CART_ID) REFERENCES SHOP_CART(CART_ID), /* (many to one relation with shop_cart table) */
CATEGORY_ID INT,
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) /* (many to one relation with category table) */);

CREATE TABLE CATEGORY(
CATEGORY_ID INT PRIMARY KEY,
CATEGORY_NAME VARCHAR(30),
DESCRIPTION VARCHAR(30),
CREATED_BY VARCHAR(30),
CREATED_ON DATE,
UPDATED_BY VARCHAR(30),
UPDATED_ON DATE
);

CREATE TABLE ORDER_DETAIL(
ORDER_ID INT PRIMARY KEY,
ADDRESS VARCHAR(30),
STATUS VARCHAR(30),
USER_ID INT,
CREATED_BY VARCHAR(30),
CREATED_ON DATE,
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
); 